# Copyright 2019 Nokia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Use newer than the CentOS stock diskimage-builder via "cloud" repo
FROM centos:7.5.1804
RUN \
    yum-config-manager --add-repo http://mirror.centos.org/centos/7/cloud/x86_64/openstack-queens/ && \
    yum install --nogpgcheck -y diskimage-builder \
        git \
        python \
        wget \
        which \
        findutils \
        systemd-udev \
        PyYAML \
        parted \
        sudo \
        e2fsprogs \
        xfsprogs

WORKDIR /work
