#!/bin/bash
# Copyright 2019 Nokia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

yum info installed > /root/yum_info_installed
rpm -qai --queryformat "Obsoletes   : [%{OBSOLETES},]\n" > /root/rpm_info_installed

# Collect bills of material, RPM subcomponent lists
boms_dir=/root/boms
mkdir $boms_dir
for bom_path in $(rpm -qal | egrep "/[^/]+-bom.json$" || :); do
    cp $bom_path $boms_dir/$(rpm -qf $bom_path)
done
